using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AISEP.DAL.Migrations
{
    /// <inheritdoc />
    public partial class AddProjectFollowers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"DROP TABLE IF EXISTS ""startup_followers"" CASCADE;");
            migrationBuilder.Sql(
                @"DO $$
BEGIN
    IF to_regclass('public.project_followers') IS NULL THEN
        CREATE TABLE ""project_followers"" (
            ""ProjectFollowerId"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ""FollowerId"" integer NOT NULL,
            ""ProjectId"" integer NOT NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_project_followers"" PRIMARY KEY (""ProjectFollowerId"")
        );
    END IF;
END $$;");

            migrationBuilder.Sql(
                @"DO $$
BEGIN
    IF to_regclass('public.project_followers') IS NOT NULL
       AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_project_followers_projects_ProjectId'
              AND conrelid = 'project_followers'::regclass
       ) THEN
        ALTER TABLE ""project_followers""
            ADD CONSTRAINT ""FK_project_followers_projects_ProjectId""
            FOREIGN KEY (""ProjectId"") REFERENCES ""projects"" (""ProjectId"") ON DELETE CASCADE;
    END IF;

    IF to_regclass('public.project_followers') IS NOT NULL
       AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_project_followers_users_FollowerId'
              AND conrelid = 'project_followers'::regclass
       ) THEN
        ALTER TABLE ""project_followers""
            ADD CONSTRAINT ""FK_project_followers_users_FollowerId""
            FOREIGN KEY (""FollowerId"") REFERENCES ""users"" (""Id"") ON DELETE CASCADE;
    END IF;
END $$;");

            migrationBuilder.Sql(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_project_followers_FollowerId_ProjectId"" ON ""project_followers"" (""FollowerId"", ""ProjectId"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_project_followers_ProjectId"" ON ""project_followers"" (""ProjectId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "project_followers");
        }
    }
}
