using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AISEP.DAL.Migrations
{
    /// <inheritdoc />
    public partial class RefactorStartupFollowersToProjectFollowers : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"DO $$
BEGIN
    IF to_regclass('public.project_followers') IS NULL THEN
        CREATE TABLE ""project_followers"" (
            ""ProjectFollowerId"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ""FollowerId"" integer NOT NULL,
            ""ProjectId"" integer NOT NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_project_followers"" PRIMARY KEY (""ProjectFollowerId"")
        );
    END IF;
END $$;");

            migrationBuilder.Sql(
                @"DO $$
BEGIN
    IF to_regclass('public.project_followers') IS NOT NULL
       AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_project_followers_projects_ProjectId'
              AND conrelid = 'project_followers'::regclass
       ) THEN
        ALTER TABLE ""project_followers""
            ADD CONSTRAINT ""FK_project_followers_projects_ProjectId""
            FOREIGN KEY (""ProjectId"") REFERENCES ""projects"" (""ProjectId"") ON DELETE CASCADE;
    END IF;

    IF to_regclass('public.project_followers') IS NOT NULL
       AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_project_followers_users_FollowerId'
              AND conrelid = 'project_followers'::regclass
       ) THEN
        ALTER TABLE ""project_followers""
            ADD CONSTRAINT ""FK_project_followers_users_FollowerId""
            FOREIGN KEY (""FollowerId"") REFERENCES ""users"" (""Id"") ON DELETE CASCADE;
    END IF;
END $$;");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_project_followers_FollowerId"" ON ""project_followers"" (""FollowerId"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_project_followers_ProjectId"" ON ""project_followers"" (""ProjectId"");");

            migrationBuilder.Sql(
                @"DROP TABLE IF EXISTS ""startup_followers"" CASCADE;");

            migrationBuilder.Sql(
                @"DROP TABLE IF EXISTS ""project_follow"" CASCADE;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"DROP TABLE IF EXISTS ""project_followers"" CASCADE;");

            migrationBuilder.Sql(
                @"DO $$
BEGIN
    IF to_regclass('public.startup_followers') IS NULL THEN
        CREATE TABLE ""startup_followers"" (
            ""StartupFollowerId"" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            ""FollowedId"" integer NOT NULL,
            ""FollowerId"" integer NOT NULL,
            ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT ""PK_startup_followers"" PRIMARY KEY (""StartupFollowerId""),
            CONSTRAINT ""FK_startup_followers_startups_FollowedId"" FOREIGN KEY (""FollowedId"") REFERENCES ""startups"" (""StartupId"") ON DELETE CASCADE,
            CONSTRAINT ""FK_startup_followers_users_FollowerId"" FOREIGN KEY (""FollowerId"") REFERENCES ""users"" (""Id"") ON DELETE CASCADE
        );
    END IF;
END $$;");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_startup_followers_FollowedId"" ON ""startup_followers"" (""FollowedId"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_startup_followers_FollowerId"" ON ""startup_followers"" (""FollowerId"");");
        }
    }
}
